theme: jekyll-theme-cayman
title: taironemagalhaes/phd-thesis-audio
description: Audio excerpts referenced in my PhD thesis, entitled "Methods of Audio Content Analysis for the Empirical Study of Clarinet Performances"
show_downloads: false
author:
  name      : Tairone Nunes Magalhães